[project]
name = "Research"
version = "0.0.1"
description = "Research"

[build-system]
requires = ["setuptools", "wheel"]

[tool.black]
line-length = 120
target-version = ['py38', 'py39', 'py310', 'py311']