name: Pylint

on: [push]
jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.11"]
    steps:
      - uses: conda-incubator/setup-miniconda@v3
      - uses: actions/checkout@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          conda install --file ../envs/nav.yml


#jobs:
#  setup-conda:
#    runs-on: ubuntu-latest
##    defaults:
##      run:
##        shell: bash -el {0}
#    steps:
##      - uses: actions/checkout@v4
#      - uses: conda-incubator/setup-miniconda@v3
#        with:
#          auto-update-conda: true
#          python-version: 3.11
#          activate-environment: nav
#          environment-file: ../envs/nav.yml
#      - run: conda info
#      - run: conda install -c conda-forge pylint
  #build:
  #  runs-on: ubuntu-latest
  #  strategy:
  #    matrix:
  #      python-version: ["3.9", "3.10", "3.11"]
  #  steps:
  #  - uses: actions/checkout@v3
  #  - name: Set up Python ${{ matrix.python-version }}
  #    uses: actions/setup-python@v3
  #    with:
  #      python-version: ${{ matrix.python-version }}
  #  - name: Install dependencies
  #    run: |
  #      python -m pip install --upgrade pip
  #      pip install pylint
  #      pip install -r requirements.txt
  #  - name: Analysing the code with pylint
  #    run: |
  #      pylint $(git ls-files '*.py')
