name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: /envs/nav.yml
        activate-environment: nav
    - name: Install dependencies
      run: |
        conda update --all
        conda install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
