name: Pylint

on: [push]

jobs:
  default-shell:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v3
      - run: ls -la
      - run: conda env create --file ../envs/nav.yml
      - run: conda activate nav
      - run: conda info
      - run: conda install -c conda-forge pylint
  #build:
  #  runs-on: ubuntu-latest
  #  strategy:
  #    matrix:
  #      python-version: ["3.9", "3.10", "3.11"]
  #  steps:
  #  - uses: actions/checkout@v3
  #  - name: Set up Python ${{ matrix.python-version }}
  #    uses: actions/setup-python@v3
  #    with:
  #      python-version: ${{ matrix.python-version }}
  #  - name: Install dependencies
  #    run: |
  #      python -m pip install --upgrade pip
  #      pip install pylint
  #      pip install -r requirements.txt
  #  - name: Analysing the code with pylint
  #    run: |
  #      pylint $(git ls-files '*.py')
