name: Pylint

on: [push]
jobs:
  default-shell:
    name: Default shell
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: nav
          environment-file: envs/nav.yml
      - run: conda install pylist
      - run: pylint $(git ls-files '*.py')